PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.astronergy.com  (China)
    Flags=$0041
    Manufacturer=Astronergy
    Model=CHSM 6612P-295
    DataSource=Manufacturer 2011
    YearBeg=2011
    Width=0.994
    Height=1.956
    Depth=0.050
    Weight=23.500
    NPieces=100
    PriceDate=23/12/18 04:08
    Remarks, Count=5
      Str_1=Frame: aluminium
      Str_2=Structure: Glass Tedlar
      Str_3=Connections: MC4 Compatible
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiPoly
  NCelS=72
  NCelP=1
  NDiode=6
  GRef=1000
  TRef=25.0
  PNom=295.0
  PNomTolLow=-3.00
  PNomTolUp=3.00
  Isc=9.160
  Voc=45.03
  Imp=8.300
  Vmp=35.72
  muISC=7.97
  muVocSpec=-127.9
  muPmpReq=-0.451
  RShunt=200
  Rp_0=800
  Rp_Exp=5.50
  RSerie=0.484
  Gamma=1.112
  muGamma=-0.0008
  VMaxIEC=1000
  Absorb=0.90
  ARev=3.200
  BRev=10.992
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=243.3
  SandiaAMCorr=50.000
End of PVObject pvModule
