PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.auxinsolar.com (USA)
    Flags=$0041
    Manufacturer=Auxin Solar
    Model=AXN6P612T335
    DataSource=Manufacturer 2017
    YearBeg=2014
    Width=0.992
    Height=1.956
    Depth=0.040
    Weight=21.400
    NPieces=100
    PriceDate=21/12/18 02:06
    Remarks, Count=5
      Str_1=Frame: Anodized alu (siver and black)
      Str_2
      Str_3=Connections: MC4/Tyco compatible, customizable
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiPoly
  NCelS=72
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=335.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  Isc=9.560
  Voc=46.37
  Imp=8.920
  Vmp=37.55
  muISC=4.78
  muVocSpec=-148.4
  muPmpReq=-0.420
  RShunt=300
  Rp_0=1200
  Rp_Exp=5.50
  RSerie=0.371
  Gamma=1.026
  muGamma=-0.0006
  VMaxIEC=1000
  Absorb=0.90
  ARev=3.200
  BRev=11.472
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=243.4
  SandiaAMCorr=50.000
End of PVObject pvModule
