PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.auxinsolar.com (USA)
    Flags=$0041
    Manufacturer=Auxin Solar
    Model=AXN6P612T300
    DataSource=Manufacturer 2017
    YearBeg=2014
    Width=0.992
    Height=1.956
    Depth=0.040
    Weight=21.400
    NPieces=100
    PriceDate=23/12/18 05:13
    Remarks, Count=5
      Str_1=Frame: Anodized alu (siver and black)
      Str_2
      Str_3=Connections: MC4/Tyco compatible, customizable
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiPoly
  NCelS=72
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=300.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  Isc=8.540
  Voc=44.86
  Imp=7.970
  Vmp=37.66
  muISC=4.27
  muVocSpec=-143.6
  muPmpReq=-0.420
  RShunt=350
  Rp_0=1400
  Rp_Exp=5.50
  RSerie=0.297
  Gamma=0.901
  muGamma=-0.0005
  VMaxIEC=1000
  Absorb=0.90
  ARev=3.200
  BRev=10.248
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=243.4
  SandiaAMCorr=50.000
End of PVObject pvModule
