PVObject_=pvModule
  Version=6.78
  Flags=$0543

  PVObject_Commercial=pvCommercial
    Comment=Axitec Energy GmbH & Co. KG  www.axitecsolar.com
    Flags=$0041
    Manufacturer=Axitec Energy
    Model=AXIperfect AC-305T/156-60S
    DataSource=Manufacturer 2016
    YearBeg=2016
    Width=0.992
    Height=1.640
    Depth=0.040
    Weight=19.600
    NPieces=100
    PriceDate=23/12/18 05:39
    Remarks, Count=5
      Str_1=Frame: Anodized alu frame
      Str_2=Structure: 3.2 mm hardened glass
      Str_3=Connections: Amphenol H4
      Str_4=Monocrystalline, Thinfilm Tunnel technology
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=60
  NCelP=1
  NDiode=3
  FrontSurface=fsNormalGlass
  GRef=1000
  TRef=25.0
  PNom=305.0
  PNomTolLow=0.00
  PNomTolUp=1.63
  Isc=9.000
  Voc=43.60
  Imp=8.270
  Vmp=36.90
  muISC=3.60
  muVocSpec=-109.0
  muPmpReq=-0.260
  RShunt=250
  Rp_0=1000
  Rp_Exp=5.50
  RSerie=0.170
  Gamma=1.264
  muGamma=0.0002
  VMaxIEC=1000
  Absorb=0.90
  ARev=3.200
  BRev=10.800
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=243.4
  SandiaAMCorr=50.000
End of PVObject pvModule
