PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=Axitec Energy GmbH & Co. KG  www.axitecsolar.com
    Flags=$0041
    Manufacturer=Axitec Energy
    Model=AXIpremium AC-310M/60S
    DataSource=Manufacturer 2018
    YearBeg=2018
    Width=0.992
    Height=1.640
    Depth=0.035
    Weight=18.000
    NPieces=100
    PriceDate=23/12/18 06:35
    Remarks, Count=5
      Str_1=Frame: Anodized alu frame
      Str_2=Structure: 3.2 mm hardened glass
      Str_3=Connections: MC4 pluggable
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=60
  NCelP=1
  NDiode=3
  FrontSurface=fsNormalGlass
  GRef=1000
  TRef=25.0
  PNom=310.0
  PNomTolLow=0.00
  PNomTolUp=1.58
  Isc=9.950
  Voc=39.94
  Imp=9.540
  Vmp=32.51
  muISC=3.98
  muVocSpec=-115.8
  muPmpReq=-0.390
  RShunt=400
  Rp_0=1600
  Rp_Exp=5.50
  RSerie=0.243
  Gamma=0.976
  muGamma=-0.0005
  VMaxIEC=1000
  Absorb=0.90
  ARev=3.200
  BRev=11.940
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=243.4
  SandiaAMCorr=50.000
End of PVObject pvModule
