PVObject_=pvModule
  Version=6.78
  Flags=$0443

  PVObject_Commercial=pvCommercial
    Comment=www.benqsolar.com
    Flags=$0041
    Manufacturer=BenQ Solar
    Model=PM096B00_330
    DataSource=Manufacturer 2014
    YearBeg=2013
    Width=1.046
    Height=1.559
    Depth=0.046
    Weight=18.600
    NPieces=100
    PriceDate=21/12/18 02:46
    Remarks, Count=5
      Str_1=Frame: Anodized aluminium
      Str_2
      Str_3=Connections: MC4 Compatible
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=96
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=330.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  Isc=6.520
  Voc=64.90
  Imp=6.040
  Vmp=54.70
  muISC=3.91
  muVocSpec=0.0
  muPmpReq=-0.380
  RShunt=1500
  Rp_0=6000
  Rp_Exp=5.50
  RSerie=0.570
  Gamma=1.022
  muGamma=-0.0007
  VMaxIEC=1000
  Absorb=0.90
  ARev=3.200
  BRev=7.824
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=152.3
  SandiaAMCorr=50.000
End of PVObject pvModule
