PVObject_=pvModule
  Version=6.78
  Flags=$0043

  PVObject_Commercial=pvCommercial
    Comment=www.bosch-solarenergy.de
    Flags=$0041
    Manufacturer=Bosch Solar Energy AG
    Model=BSM c- Si M 60plus S EU56117_V1_285Wp
    DataSource=Manufacturer 2013
    YearBeg=2013
    Width=0.990
    Height=1.674
    Depth=0.046
    Weight=19.800
    NPieces=100
    PriceDate=23/12/18 01:26
    Remarks, Count=5
      Str_1=Frame: alu black
      Str_2=Structure: MC 4
      Str_3=Connections: half cell module
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=60
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=285.0
  PNomTolLow=0.00
  PNomTolUp=2.00
  Isc=9.560
  Voc=39.13
  Imp=9.080
  Vmp=31.42
  muISC=4.30
  muVocSpec=-121.3
  muPmpReq=-0.420
  RShunt=400
  Rp_0=1600
  Rp_Exp=5.50
  RSerie=0.260
  Gamma=1.099
  muGamma=-0.0006
  VMaxIEC=1000
  Absorb=0.90
  ARev=3.200
  BRev=11.200
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=241.0
  SandiaAMCorr=50.000
End of PVObject pvModule
