PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.centrosolar.com
    Flags=$0041
    Manufacturer=Centrosolar
    Model=S 215P54 Vision
    DataSource=Manufacturer 2012
    YearBeg=2012
    Width=0.983
    Height=1.496
    Depth=0.006
    Weight=21.000
    NPieces=100
    PriceDate=22/12/18 14:43
    Remarks, Count=5
      Str_1=Frame: Frameless
      Str_2
      Str_3=Connections: Cable Lapp
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiPoly
  NCelS=54
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=215.0
  PNomTolLow=-3.00
  PNomTolUp=3.00
  Isc=8.820
  Voc=33.57
  Imp=8.180
  Vmp=26.29
  muISC=2.47
  muVocSpec=0.0
  muPmpReq=-0.450
  RShunt=200
  Rp_0=800
  Rp_Exp=5.50
  RSerie=0.352
  Gamma=1.120
  muGamma=-0.0002
  VMaxIEC=1000
  Absorb=0.90
  ARev=3.200
  BRev=10.584
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=237.4
  SandiaAMCorr=50.000
End of PVObject pvModule
