PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.csun-solar.com
    Flags=$0041
    Manufacturer=CSUN Solar
    Model=CSUN 280-72P
    DataSource=Manufacturer 2013
    YearBeg=2009
    Width=0.990
    Height=1.956
    Depth=0.050
    Weight=22.300
    NPieces=100
    PriceDate=23/12/18 00:56
    Remarks, Count=5
      Str_1=Frame: aluminium
      Str_2=Structure: Glass
      Str_3=Connections: MC4
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiPoly
  NCelS=72
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=280.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  Isc=8.580
  Voc=44.00
  Imp=7.940
  Vmp=35.30
  muISC=3.86
  muVocSpec=-128.5
  muPmpReq=-0.408
  RShunt=300
  Rp_0=1200
  Rp_Exp=5.50
  RSerie=0.427
  Gamma=1.033
  muGamma=0.0000
  VMaxIEC=1000
  Absorb=0.90
  ARev=3.200
  BRev=10.296
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  SandiaAMCorr=50.000
End of PVObject pvModule
