PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.csun-solar.com
    Flags=$0041
    Manufacturer=CSUN Solar
    Model=CSUN 360-72MH
    DataSource=Manufacturer 2017
    YearBeg=2017
    Width=0.990
    Height=1.956
    Depth=0.040
    Weight=22.100
    NPieces=100
    PriceDate=21/12/18 00:38
    Remarks, Count=5
      Str_1=Frame: aluminium
      Str_2=Structure: Glass
      Str_3=Connections: MC4
      Str_4=1500V Series
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=72
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=360.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  Isc=9.650
  Voc=47.30
  Imp=9.320
  Vmp=38.60
  muISC=3.76
  muVocSpec=-145.2
  muPmpReq=-0.423
  RShunt=600
  Rp_0=2500
  Rp_Exp=5.50
  RSerie=0.261
  Gamma=0.945
  muGamma=-0.0007
  VMaxIEC=1500
  Absorb=0.90
  ARev=3.200
  BRev=11.580
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  SandiaAMCorr=50.000
End of PVObject pvModule
