PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.daqosolar.com (China)
    Flags=$0041
    Manufacturer=DAQO
    Model=DQ320MSD
    DataSource=Manufacturer 2014
    YearBeg=2014
    YearEnd=2018
    Width=0.992
    Height=1.956
    Depth=0.040
    Weight=22.000
    NPieces=100
    PriceDate=21/12/18 03:46
    Remarks, Count=5
      Str_1=Frame: Aluminium
      Str_2=Structure: 3.2 mm tempered
      Str_3=Connections: MC-4
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=72
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=320.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  Isc=8.980
  Voc=45.10
  Imp=8.670
  Vmp=36.90
  muISC=4.49
  muVocSpec=-144.3
  muPmpReq=-0.440
  RShunt=600
  Rp_0=2500
  Rp_Exp=5.50
  RSerie=0.258
  Gamma=0.900
  muGamma=-0.0007
  VMaxIEC=1000
  VMaxUL=600
  Absorb=0.90
  ARev=3.200
  BRev=10.776
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=237.4
  SandiaAMCorr=50.000
End of PVObject pvModule
