PVObject_=pvModule
  Version=6.78
  Flags=$0063

  PVObject_Commercial=pvCommercial
    Comment=http://www2.dupont.com/Apollo/en_HK/index.html
    Flags=$0041
    Manufacturer=DuPont Apollo
    Model=DA148-C1
    DataSource=Manufacturer 2011
    YearBeg=2010
    Width=1.110
    Height=1.409
    Depth=0.035
    Weight=20.000
    NPieces=100
    PriceDate=22/12/18 10:47
    Remarks, Count=5
      Str_1=Frame: aluminium
      Str_2=Structure: Glass (low iron) / EVA/BACKSHEET
      Str_3=Connections: MC4 Cmpatiable
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtuCSi_aSiH
  NCelS=119
  NCelP=1
  NDiode=1
  GRef=1000
  TRef=25.0
  PNom=148.0
  PNomTolLow=-5.00
  PNomTolUp=5.00
  Isc=1.500
  Voc=157.00
  Imp=1.210
  Vmp=122.00
  muISC=1.30
  muVocSpec=0.0
  muPmpReq=-0.300
  RShunt=1330
  Rp_0=10000
  Rp_Exp=5.50
  RSerie=13.000
  Gamma=3.023
  muGamma=0.0105
  D2MuTau=2.800
  VMaxIEC=1000
  Absorb=0.90
  ARev=3.200
  BRev=1.800
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=122.0
  SandiaAMCorr=50.000
End of PVObject pvModule
