PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.eastechsolar.com (Spain)
    Flags=$0041
    Manufacturer=Eastech Solar
    Model=ESF-290MA
    DataSource=Manufacturer 2011
    YearBeg=2011
    Width=0.990
    Height=1.960
    Depth=0.046
    NPieces=100
    PriceDate=23/12/18 02:33
    Remarks, Count=5
      Str_1=Frame: aluminium
      Str_2=Structure: Glass Tedlar
      Str_3=Connections: ECM4M, ECM4H, ECT4M, ECT4H
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=72
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=290.0
  PNomTolLow=-3.00
  PNomTolUp=5.00
  Isc=8.290
  Voc=45.07
  Imp=7.760
  Vmp=37.44
  muISC=2.98
  muVocSpec=0.0
  muPmpReq=-0.370
  RShunt=350
  Rp_0=1400
  Rp_Exp=5.50
  RSerie=0.343
  Gamma=0.908
  muGamma=0.0000
  VMaxIEC=1000
  Absorb=0.90
  ARev=3.200
  BRev=9.948
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=237.4
  SandiaAMCorr=50.000
End of PVObject pvModule
