PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.ecosolargy.com
    Flags=$0041
    Manufacturer=ecoSolargy
    Model=ECO285A156P-72
    DataSource=Manufacturer 2013
    YearBeg=2012
    Width=0.992
    Height=1.956
    Depth=0.050
    Weight=23.000
    NPieces=100
    PriceDate=23/12/18 02:06
    Remarks, Count=5
      Str_1=Frame: aluminium
      Str_2
      Str_3=Connections: MC Cable
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiPoly
  NCelS=72
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=285.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  Isc=8.310
  Voc=45.30
  Imp=7.890
  Vmp=36.10
  muISC=9.97
  muVocSpec=-164.9
  muPmpReq=-0.487
  RShunt=450
  Rp_0=1800
  Rp_Exp=5.50
  RSerie=0.399
  Gamma=1.028
  muGamma=-0.0015
  VMaxIEC=1000
  VMaxUL=600
  Absorb=0.90
  ARev=3.200
  BRev=9.972
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=243.4
  SandiaAMCorr=50.000
End of PVObject pvModule
