PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.ecosol-solar.com (China)
    Flags=$0041
    Manufacturer=Ecosol PV tech
    Model=Mono 270 Wp  72 cells
    DataSource=Manufacturer 2013
    YearBeg=2006
    Width=0.992
    Height=1.956
    Depth=0.050
    Weight=23.000
    NPieces=100
    PriceDate=22/12/18 22:06
    Remarks, Count=5
      Str_1=Frame: Aluminium
      Str_2=Structure: 3.2 mm tempered
      Str_3=Connections: JBox(RH701)+ cable
      Str_4=For DEMO, made in Vietnam and China
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=72
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=270.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  Isc=8.040
  Voc=44.40
  Imp=7.550
  Vmp=35.80
  muISC=3.62
  muVocSpec=-151.0
  muPmpReq=-0.470
  RShunt=350
  Rp_0=1400
  Rp_Exp=5.50
  RSerie=0.417
  Gamma=0.978
  muGamma=-0.0007
  VMaxIEC=1000
  VMaxUL=600
  Absorb=0.90
  ARev=3.200
  BRev=9.648
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=237.0
  SandiaAMCorr=50.000
End of PVObject pvModule
