PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.einnova-solarline.com (China)
    Flags=$0041
    Manufacturer=Einnova Solarline
    Model=Black ESM 340W 72 cells
    DataSource=Manufacturer 2018
    YearBeg=2017
    Width=0.992
    Height=1.956
    Depth=0.040
    Weight=21.000
    NPieces=100
    PriceDate=21/12/18 15:27
    Remarks, Count=5
      Str_1=Frame: Aluminium
      Str_2=Structure: Tempered glass - Tedlar
      Str_3=Connections: JBox+ cable
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=72
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=340.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  Isc=9.700
  Voc=46.40
  Imp=8.880
  Vmp=38.30
  muISC=4.85
  muVocSpec=0.0
  muPmpReq=-0.390
  RShunt=240
  Rp_0=1000
  Rp_Exp=5.50
  RSerie=0.367
  Gamma=0.982
  muGamma=-0.0003
  VMaxIEC=1000
  VMaxUL=600
  Absorb=0.90
  ARev=3.200
  BRev=11.560
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=237.4
  SandiaAMCorr=50.000
End of PVObject pvModule
