PVObject_=pvModule
  Version=6.78
  Flags=$0043

  PVObject_Commercial=pvCommercial
    Comment=www.etsolar.com  (China)
    Flags=$0041
    Manufacturer=ET Solar
    Model=ET-M660285WW
    DataSource=Manufacturer 2016
    YearBeg=2016
    Width=0.992
    Height=1.640
    Depth=0.035
    Weight=18.500
    NPieces=100
    PriceDate=23/12/18 01:31
    Remarks, Count=5
      Str_1=Frame: Anodized aluminium
      Str_2=Structure: Tempered glass / EVA / Multilayer back sheet
      Str_3=Connections: MC4 or MC4 compatible
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=60
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=285.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  Isc=9.460
  Voc=39.18
  Imp=8.950
  Vmp=31.85
  muISC=4.73
  muVocSpec=0.0
  muPmpReq=-0.420
  RShunt=700
  Rp_0=4000
  Rp_Exp=5.50
  RSerie=0.328
  Gamma=0.948
  muGamma=-0.0006
  VMaxIEC=1000
  VMaxUL=1000
  Absorb=0.90
  ARev=3.200
  BRev=11.352
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=244.3
  SandiaAMCorr=50.000
End of PVObject pvModule
