PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Flags=$0041
    Manufacturer=Exiom Solution
    Model=Mono 260 Wp 96 cells
    DataSource=Manufacturer 2016
    YearBeg=2016
    Width=1.069
    Height=1.580
    Depth=0.040
    Weight=20.500
    NPieces=100
    PriceDate=22/12/18 20:06
    Remarks, Count=5
      Str_1
      Str_2
      Str_3
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=96
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=260.0
  PNomTolLow=0.00
  PNomTolUp=5.00
  Isc=5.690
  Voc=60.70
  Imp=5.310
  Vmp=49.00
  muISC=2.85
  muVocSpec=-202.7
  muPmpReq=-0.445
  RShunt=650
  Rp_0=2500
  Rp_Exp=5.50
  RSerie=0.835
  Gamma=1.013
  muGamma=-0.0006
  VMaxIEC=1000
  VMaxUL=600
  Absorb=0.90
  ARev=3.200
  BRev=6.828
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  SandiaAMCorr=50.000
End of PVObject pvModule
