PVObject_=pvModule
  Version=6.78
  Flags=$0043

  PVObject_Commercial=pvCommercial
    Comment=www.firstsolar.com   (USA)
    Flags=$0041
    Manufacturer=First Solar
    Model=FS-397-PLUS
    DataSource=Manufacturer Jan 2014
    YearBeg=2014
    Width=0.600
    Height=1.200
    Depth=0.007
    Weight=12.000
    NPieces=100
    PriceDate=22/12/18 00:33
    Remarks, Count=5
      Str_1=Frame: Laminate
      Str_2=Structure: Glass-Polyolefin-Glass
      Str_3=Connections: MC4 Connectors
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtCdTe
  NCelS=73
  NCelP=2
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=97.5
  PNomTolLow=-5.00
  PNomTolUp=5.00
  Isc=2.290
  Voc=58.60
  Imp=2.110
  Vmp=46.10
  muISC=0.89
  muVocSpec=-195.1
  muPmpReq=-0.290
  RShunt=3900
  Rp_0=10250
  Rp_Exp=5.10
  RSerie=1.810
  Gamma=1.399
  muGamma=0.0010
  D2MuTau=0.860
  VMaxIEC=1000
  Absorb=0.90
  ARev=3.200
  BRev=3.920
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=44.7
  SandiaAMCorr=50.000
End of PVObject pvModule
