PVObject_=pvModule
  Version=6.78
  Flags=$00800743

  PVObject_Commercial=pvCommercial
    Comment=www.gclsi.com  (China)
    Flags=$0041
    Manufacturer=GCL
    Model=GCL-M6/72GDF-365
    DataSource=Manufacturer 2018
    YearBeg=2018
    Width=0.998
    Height=1.974
    Depth=0.030
    Weight=29.000
    NPieces=100
    PriceDate=23/12/18 08:43
    Remarks, Count=5
      Str_1=Frame: none
      Str_2=Structure: 2.5 mm High transparency solar glass
      Str_3=Connections: EVA+Float solar glass, JBox + Cables
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=72
  NCelP=1
  NDiode=3
  FrontSurface=fsNormalGlass
  GRef=1000
  TRef=25.0
  PNom=365.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  BifacialityFactor=0.710
  Isc=9.800
  Voc=47.93
  Imp=9.330
  Vmp=39.13
  muISC=5.88
  muVocSpec=-143.8
  muPmpReq=-0.380
  RShunt=400
  Rp_0=1600
  Rp_Exp=5.50
  RSerie=0.312
  Gamma=0.978
  muGamma=-0.0006
  VMaxIEC=1500
  VMaxUL=1500
  Absorb=0.90
  ARev=3.200
  BRev=11.760
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=249.9
  SandiaAMCorr=50.000
End of PVObject pvModule
