PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.gclsi.com  (China)
    Flags=$0041
    Manufacturer=GCL
    Model=GCL-M6/60H-295
    DataSource=Manufacturer 2017
    YearBeg=2015
    Width=0.992
    Height=1.640
    Depth=0.035
    Weight=18.100
    NPieces=100
    PriceDate=23/12/18 03:41
    Remarks, Count=5
      Str_1=Frame: Aluminium
      Str_2=Structure: 3.2 mm High transparency solar glass
      Str_3=Connections: EVA + PVDF backsheet, JBox + Cables
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=60
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=295.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  Isc=9.690
  Voc=39.30
  Imp=9.160
  Vmp=32.20
  muISC=5.81
  muVocSpec=-117.9
  muPmpReq=-0.380
  RShunt=300
  Rp_0=1200
  Rp_Exp=5.50
  RSerie=0.268
  Gamma=0.967
  muGamma=-0.0005
  VMaxIEC=1500
  VMaxUL=1500
  Absorb=0.90
  ARev=3.200
  BRev=11.628
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=249.9
  SandiaAMCorr=50.000
End of PVObject pvModule
