PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.gclsi.com  (China)
    Flags=$0041
    Manufacturer=GCL
    Model=GCL-P6/72H-400
    DataSource=Manufacturer 2018
    YearBeg=2018
    Width=0.992
    Height=1.956
    Depth=0.035
    Weight=22.200
    NPieces=100
    PriceDate=21/12/18 14:42
    Remarks, Count=5
      Str_1=Frame: Aluminium
      Str_2=Structure: 3.2 High transparency solar glass
      Str_3=Connections: EVA + PVDF backsheet, JBox + Cables
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiPoly
  NCelS=72
  NCelP=1
  NDiode=3
  FrontSurface=fsNormalGlass
  GRef=1000
  TRef=25.0
  PNom=400.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  Isc=10.280
  Voc=50.60
  Imp=9.470
  Vmp=42.25
  muISC=5.14
  muVocSpec=-151.8
  muPmpReq=-0.380
  RShunt=250
  Rp_0=1000
  Rp_Exp=5.50
  RSerie=0.332
  Gamma=1.023
  muGamma=-0.0009
  VMaxIEC=1500
  VMaxUL=1500
  Absorb=0.90
  ARev=3.200
  BRev=12.336
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=252.0
  SandiaAMCorr=50.000
End of PVObject pvModule
