PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.gclsi.com  (China)
    Flags=$0041
    Manufacturer=GCL
    Model=GCL-M3/72H-365
    DataSource=Manufacturer 2018
    YearBeg=2018
    Width=0.992
    Height=1.986
    Depth=0.035
    Weight=22.600
    NPieces=100
    PriceDate=21/12/18 14:59
    Remarks, Count=5
      Str_1=Frame: Aluminium
      Str_2=Structure: 3.2 High transparency solar glass
      Str_3=Connections: EVA + PVDF backsheet, JBox + Cables
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=72
  NCelP=2
  NDiode=3
  SubModuleLayout=slTwinHalfCells
  FrontSurface=fsNormalGlass
  GRef=1000
  TRef=25.0
  PNom=365.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  Isc=9.670
  Voc=47.73
  Imp=9.130
  Vmp=40.00
  muISC=5.80
  muVocSpec=-143.2
  muPmpReq=-0.380
  RShunt=350
  Rp_0=1400
  Rp_Exp=5.50
  RSerie=0.246
  Gamma=0.955
  muGamma=-0.0006
  VMaxIEC=1500
  VMaxUL=1500
  Absorb=0.90
  ARev=3.200
  BRev=11.604
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=124.9
  SandiaAMCorr=50.000
End of PVObject pvModule
