PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.globalsolar.com (U.S.A)
    Flags=$0041
    Manufacturer=Global Solar Energy
    Model=FG-1BTM-300
    DataSource=Manufacturer 2017
    YearBeg=2011
    Width=0.494
    Height=5.742
    Depth=0.003
    Weight=9.300
    NPieces=100
    PriceDate=23/12/18 05:36
    Remarks, Count=6
      Str_1=Frame: Frameless (Flexible thin film)
      Str_2=Structure: Low Reflective ETFE (Protects from UV, Moisture and
      Str_3=Soil)
      Str_4
      Str_5
      Str_6
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtCIS
  NCelS=108
  NCelP=1
  NDiode=1
  FrontSurface=fsARCoating
  GRef=1000
  TRef=25.0
  PNom=300.0
  PNomTolLow=-7.00
  PNomTolUp=10.00
  Isc=6.400
  Voc=69.70
  Imp=5.520
  Vmp=54.30
  muISC=-1.92
  muVocSpec=-230.0
  muPmpReq=-0.428
  RShunt=300
  Rp_0=1200
  Rp_Exp=5.50
  RSerie=1.254
  Gamma=1.404
  muGamma=-0.0001
  VMaxIEC=1000
  VMaxUL=600
  Absorb=0.90
  ARev=3.200
  BRev=7.680
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=210.0
  SandiaAMCorr=50.000
End of PVObject pvModule
