PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.heckert-solar.com (Germany)
    Flags=$0041
    Manufacturer=Heckert Solar
    Model=NeMo 2.0 60 P 255
    DataSource=Manufacturer 2018
    YearBeg=2017
    Width=1.006
    Height=1.670
    Depth=0.038
    Weight=18.300
    NPieces=100
    PriceDate=22/12/18 19:41
    Remarks, Count=5
      Str_1=Frame: Aluminium
      Str_2=Structure: Tempered glas - Tedlar
      Str_3=Connections: Jbox + Cable Tyco
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiPoly
  NCelS=60
  NCelP=1
  NDiode=3
  FrontSurface=fsARCoating
  GRef=1000
  TRef=25.0
  PNom=255.0
  PNomTolLow=0.00
  PNomTolUp=2.00
  Isc=8.810
  Voc=37.87
  Imp=8.220
  Vmp=31.02
  muISC=4.41
  muVocSpec=-117.4
  muPmpReq=-0.390
  RShunt=250
  Rp_0=1000
  Rp_Exp=5.50
  RSerie=0.313
  Gamma=0.949
  muGamma=-0.0002
  VMaxIEC=1000
  Absorb=0.90
  ARev=3.200
  BRev=10.572
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=243.4
  SandiaAMCorr=50.000
End of PVObject pvModule
