PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.heliosenergy.es  (Spain)
    Flags=$0041
    Manufacturer=Helios Energy Europe
    Model=96M-390
    DataSource=Manufacturer 2012
    YearBeg=2012
    Width=1.310
    Height=1.976
    Depth=0.040
    Weight=31.300
    NPieces=100
    PriceDate=20/12/18 23:38
    Remarks, Count=5
      Str_1=Frame: Aluminium
      Str_2=Structure: 4.0 mm glass - EVA - Polyester
      Str_3=Connections: Cable MC compatible
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=96
  NCelP=1
  NDiode=4
  GRef=1000
  TRef=25.0
  PNom=390.0
  PNomTolLow=-3.00
  PNomTolUp=3.00
  Isc=8.620
  Voc=59.30
  Imp=8.140
  Vmp=47.91
  muISC=6.03
  muVocSpec=0.0
  muPmpReq=-0.440
  RShunt=500
  Rp_0=2000
  Rp_Exp=5.50
  RSerie=0.492
  Gamma=0.967
  muGamma=-0.0006
  VMaxIEC=1000
  Absorb=0.90
  ARev=3.200
  BRev=10.344
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=238.9
  SandiaAMCorr=50.000
End of PVObject pvModule
