PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=Hyundai Heavy Industries, Korea
    Flags=$0041
    Manufacturer=Hyundai
    Model=HIS-S293MI
    DataSource=Manufacturer 2011
    YearBeg=2011
    Width=0.987
    Height=1.966
    Depth=0.050
    Weight=25.000
    NPieces=100
    PriceDate=23/12/18 03:29
    Remarks, Count=5
      Str_1=Frame: Anodized alu
      Str_2=Structure: Tempered glass 3.2 mm - EVA
      Str_3=Connections: Cables
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=72
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=293.0
  PNomTolLow=-3.00
  PNomTolUp=3.00
  Isc=8.300
  Voc=45.00
  Imp=7.900
  Vmp=37.10
  muISC=4.32
  muVocSpec=0.0
  muPmpReq=-0.440
  RShunt=450
  Rp_0=1800
  Rp_Exp=5.50
  RSerie=0.313
  Gamma=0.902
  muGamma=-0.0006
  VMaxIEC=1000
  Absorb=0.90
  ARev=3.200
  BRev=9.960
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=237.4
  SandiaAMCorr=50.000
End of PVObject pvModule
