PVObject_=pvModule
  Version=6.78
  Flags=$0543

  PVObject_Commercial=pvCommercial
    Comment=www.jasolar.com (China,Germany)
    Flags=$0041
    Manufacturer=JA Solar
    Model=JAP6(BK) 60-250/3BB
    DataSource=Manufacturer 2014
    YearBeg=2013
    Width=0.991
    Height=1.650
    Depth=0.040
    Weight=18.200
    NPieces=100
    PriceDate=22/12/18 18:44
    Remarks, Count=5
      Str_1
      Str_2
      Str_3
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiPoly
  NCelS=60
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=250.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  Isc=8.920
  Voc=37.66
  Imp=8.350
  Vmp=29.94
  muISC=5.35
  muVocSpec=-124.3
  muPmpReq=-0.410
  RShunt=250
  Rp_0=1000
  Rp_Exp=5.50
  RSerie=0.349
  Gamma=1.050
  muGamma=-0.0003
  VMaxIEC=1000
  VMaxUL=1000
  Absorb=0.90
  ARev=3.200
  BRev=10.704
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=243.4
  SandiaAMCorr=50.000
End of PVObject pvModule
