PVObject_=pvModule
  Version=6.78
  Flags=$0443

  PVObject_Commercial=pvCommercial
    Comment=www.jasolar.com (China,Germany)
    Flags=$0041
    Manufacturer=JA Solar
    Model=JAM6(L)-60-290/PR
    DataSource=Manufacturer 2014
    YearBeg=2014
    Width=0.991
    Height=1.650
    Depth=0.040
    Weight=18.200
    NPieces=100
    PriceDate=23/12/18 02:43
    Remarks, Count=5
      Str_1
      Str_2
      Str_3
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=60
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=290.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  Isc=9.520
  Voc=39.31
  Imp=9.080
  Vmp=31.95
  muISC=5.71
  muVocSpec=-117.9
  muPmpReq=-0.390
  RShunt=500
  Rp_0=2000
  Rp_Exp=5.50
  RSerie=0.285
  Gamma=0.961
  muGamma=-0.0005
  VMaxIEC=1000
  VMaxUL=1000
  Absorb=0.90
  ARev=3.200
  BRev=11.424
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=242.2
  SandiaAMCorr=50.000
End of PVObject pvModule
