PVObject_=pvModule
  Version=6.78
  Flags=$02000743

  PVObject_Commercial=pvCommercial
    Comment=www.jinkosolar.com  (China)
    Flags=$0041
    Manufacturer=Jinkosolar
    Model=JKMS340M-72V Maxim
    DataSource=Manufacturer/Maxim 2017
    YearBeg=2017
    Width=0.992
    Height=1.956
    Depth=0.040
    Weight=26.500
    NPieces=100
    PriceDate=21/12/18 01:48
    Remarks, Count=6
      Str_1=Frame: Anodized Aluminium Alloy
      Str_2=Structure: 4.0mm High Transmission, Low Iron, tempered, anti-
      Str_3=reflection coating
      Str_4
      Str_5
      Str_6=Maxim optimizer MAX20800A
    End of Remarks=Maxim optimizer MAX20800A
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=72
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=340.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  Isc=9.240
  Voc=47.10
  Imp=8.790
  Vmp=38.70
  muISC=4.62
  muVocSpec=-136.6
  muPmpReq=-0.390
  RShunt=450
  Rp_0=1800
  Rp_Exp=5.50
  RSerie=0.313
  Gamma=0.948
  muGamma=-0.0005
  VMaxIEC=1000
  VMaxUL=1000
  Absorb=0.90
  ARev=3.200
  BRev=11.088
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=237.4
  SandiaAMCorr=50.000
End of PVObject pvModule
