PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.jinkosolar.com  (China)
    Flags=$0041
    Manufacturer=Jinkosolar
    Model=JKM 370M-72
    DataSource=Manufacturer 2017
    YearBeg=2017
    Width=0.992
    Height=1.956
    Depth=0.040
    Weight=26.500
    NPieces=100
    PriceDate=21/12/18 00:08
    Remarks, Count=5
      Str_1=Frame: aluminium
      Str_2=Structure: Glass/SiO2
      Str_3=Connections: EVA and High polymer material
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=72
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=370.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  Isc=9.610
  Voc=48.50
  Imp=9.280
  Vmp=39.90
  muISC=4.61
  muVocSpec=-140.6
  muPmpReq=-0.390
  RShunt=600
  Rp_0=2500
  Rp_Exp=5.50
  RSerie=0.236
  Gamma=0.967
  muGamma=-0.0007
  VMaxIEC=1000
  VMaxUL=1000
  Absorb=0.90
  ARev=3.200
  BRev=11.532
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=237.4
  SandiaAMCorr=50.000
End of PVObject pvModule
