PVObject_=pvModule
  Version=6.78
  Flags=$0043

  PVObject_Commercial=pvCommercial
    Comment=www.jolywood.cn (China)
    Flags=$0041
    Manufacturer=Jolywood
    Model=JW-D60N-285
    DataSource=Manufacturer 2017
    YearBeg=2017
    Width=0.992
    Height=1.658
    Depth=0.006
    Weight=22.500
    NPieces=100
    PriceDate=23/12/18 01:38
    Remarks, Count=5
      Str_1=Frame: Frameless
      Str_2=Structure: 2.5 mm coating tempered glass
      Str_3=Connections: F406PS/2.5 mm heat strengthened glass
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=60
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=285.0
  PNomTolLow=0.00
  PNomTolUp=1.75
  Isc=9.580
  Voc=38.60
  Imp=8.990
  Vmp=31.70
  muISC=3.83
  muVocSpec=-113.1
  muPmpReq=-0.390
  RShunt=350
  Rp_0=4000
  Rp_Exp=5.50
  RSerie=0.246
  Gamma=1.034
  muGamma=-0.0002
  VMaxIEC=1500
  VMaxUL=1000
  Absorb=0.90
  ARev=3.200
  BRev=11.496
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=237.4
  SandiaAMCorr=50.000
End of PVObject pvModule
