PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.lightwaysolar.com  (China)
    Flags=$0041
    Manufacturer=Lightwaysolar
    Model=Poly 290 Wp  72 cells
    DataSource=Manufacturer 2013
    YearBeg=2013
    Width=0.990
    Height=1.960
    Depth=0.050
    Weight=22.500
    NPieces=100
    PriceDate=23/12/18 03:21
    Remarks, Count=5
      Str_1=Frame: Aluminium
      Str_2=Structure: 3.2 mm tempered
      Str_3=Connections: MC-4
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiPoly
  NCelS=72
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=290.0
  PNomTolLow=0.00
  PNomTolUp=5.00
  Isc=8.490
  Voc=44.81
  Imp=8.110
  Vmp=35.81
  muISC=5.52
  muVocSpec=-144.3
  muPmpReq=-0.420
  RShunt=450
  Rp_0=1800
  Rp_Exp=5.50
  RSerie=0.365
  Gamma=0.980
  muGamma=-0.0005
  VMaxIEC=1000
  VMaxUL=600
  Absorb=0.90
  ARev=3.200
  BRev=10.188
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=243.4
  SandiaAMCorr=50.000
End of PVObject pvModule
