PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.lubielectronics.com  (India)
    Flags=$0041
    Manufacturer=Lubi Electronics
    Model=Mono 350 Wp  72 cells
    DataSource=Manufacturer 2018
    YearBeg=2017
    Width=0.990
    Height=1.960
    Depth=0.035
    Weight=18.300
    NPieces=100
    PriceDate=21/12/18 01:07
    Remarks, Count=5
      Str_1=Frame: Aluminium
      Str_2=Structure: 3.2 mm tempered
      Str_3=Connections: First EVA & Coveme Backsheet
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=72
  NCelP=1
  NDiode=3
  FrontSurface=fsNormalGlass
  GRef=1000
  TRef=25.0
  PNom=350.0
  PNomTolLow=-3.00
  PNomTolUp=3.00
  Isc=9.480
  Voc=46.02
  Imp=8.970
  Vmp=39.04
  muISC=4.74
  muVocSpec=-138.1
  muPmpReq=-0.350
  RShunt=400
  Rp_0=1600
  Rp_Exp=5.50
  RSerie=0.192
  Gamma=0.911
  muGamma=-0.0001
  VMaxIEC=1500
  VMaxUL=600
  Absorb=0.90
  ARev=3.200
  BRev=11.376
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=243.3
  SandiaAMCorr=50.000
End of PVObject pvModule
