PVObject_=pvModule
  Version=6.78
  Flags=$0443

  PVObject_Commercial=pvCommercial
    Comment=www.luxor-solar.com
    Flags=$0041
    Manufacturer=Luxor
    Model=LX-370M/156-72+
    DataSource=Manufacturer 2017
    YearBeg=2017
    Width=0.992
    Height=1.956
    Depth=0.040
    Weight=23.200
    NPieces=100
    PriceDate=21/12/18 00:07
    Remarks, Count=5
      Str_1=Frame: Aluminium
      Str_2=Structure: Tempered glass - Tedlar
      Str_3=Connections: MC4 or equivalent
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=72
  NCelP=1
  NDiode=3
  SubModuleLayout=slInLength
  FrontSurface=fsNormalGlass
  GRef=1000
  TRef=25.0
  PNom=370.0
  PNomTolLow=0.00
  PNomTolUp=1.80
  Isc=9.950
  Voc=47.00
  Imp=9.450
  Vmp=39.17
  muISC=5.97
  muVocSpec=-141.0
  muPmpReq=-0.400
  RShunt=1000
  Rp_0=4000
  Rp_Exp=5.50
  RSerie=0.252
  Gamma=0.960
  muGamma=-0.0006
  VMaxIEC=1000
  VMaxUL=600
  Absorb=0.90
  ARev=3.200
  BRev=11.940
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=242.6
  SandiaAMCorr=50.000
End of PVObject pvModule
