PVObject_=pvModule
  Version=6.78
  Flags=$0063

  PVObject_Commercial=pvCommercial
    Comment=www.masdarpv.com (Germany)
    Flags=$0041
    Manufacturer=Masdar PV GmbH
    Model=MPV130-M
    DataSource=Manufacturer 2011
    YearBeg=2011
    Width=1.100
    Height=1.300
    Depth=0.007
    Weight=29.500
    NPieces=100
    PriceDate=22/12/18 01:12
    Remarks, Count=5
      Str_1=Frame: frameless
      Str_2
      Str_3=Connections: J Box
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtuCSi_aSiH
  NCelS=106
  NCelP=6
  NDiode=1
  GRef=1000
  TRef=25.0
  PNom=130.0
  PNomTolLow=-5.00
  PNomTolUp=5.00
  Isc=1.330
  Voc=145.80
  Imp=1.140
  Vmp=114.20
  muISC=1.33
  muVocSpec=0.0
  muPmpReq=-0.270
  RShunt=2200
  Rp_0=38000
  Rp_Exp=5.00
  RSerie=4.000
  Gamma=2.943
  muGamma=0.0062
  D2MuTau=8.600
  VMaxIEC=1000
  Absorb=0.90
  ARev=3.200
  BRev=1.596
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  SandiaAMCorr=50.000
End of PVObject pvModule
