PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.moserbaersolar.com
    Flags=$0041
    Manufacturer=MoserBaer
    Model=MBPV CAAP BC 230Wp
    DataSource=Manufacturer 2013
    YearBeg=2012
    Width=0.991
    Height=1.661
    Depth=0.037
    Weight=18.700
    NPieces=100
    PriceDate=22/12/18 15:45
    Remarks, Count=5
      Str_1=Frame: Anodized Aluminium
      Str_2=Structure: Low iron tempered glass 3.2 mm, Tedlar
      Str_3=Connections: MC4/MC4 compatible
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiPoly
  NCelS=60
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=230.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  Isc=8.340
  Voc=37.25
  Imp=7.800
  Vmp=29.50
  muISC=0.00
  muVocSpec=0.0
  muPmpReq=-0.450
  RShunt=250
  Rp_0=1000
  Rp_Exp=5.50
  RSerie=0.378
  Gamma=1.052
  muGamma=-0.0001
  VMaxIEC=1000
  Absorb=0.90
  ARev=3.200
  BRev=10.008
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=243.4
  SandiaAMCorr=50.000
End of PVObject pvModule
