PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.photowatt.com  (France)
    Flags=$0041
    Manufacturer=Photowatt
    Model=PW2500F / 265 Wc
    DataSource=Manufacturer 2014
    YearBeg=2014
    Width=0.993
    Height=1.685
    Depth=0.040
    Weight=20.000
    NPieces=100
    PriceDate=22/12/18 21:15
    Remarks, Count=5
      Str_1=Frame: Aluminium
      Str_2=Structure: Glass Tedlar
      Str_3=Connections: Cable MC4
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=60
  NCelP=1
  NDiode=2
  GRef=1000
  TRef=25.0
  PNom=265.0
  PNomTolLow=0.00
  PNomTolUp=5.00
  Isc=9.100
  Voc=37.90
  Imp=8.600
  Vmp=30.80
  muISC=5.46
  muVocSpec=-128.9
  muPmpReq=-0.420
  RShunt=300
  Rp_0=1200
  Rp_Exp=5.50
  RSerie=0.288
  Gamma=0.962
  muGamma=-0.0005
  VMaxIEC=1000
  Absorb=0.90
  ARev=3.200
  BRev=10.920
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=237.4
  SandiaAMCorr=50.000
End of PVObject pvModule
