PVObject_=pvModule
  Version=6.78
  Flags=$0043

  PVObject_Commercial=pvCommercial
    Comment=www.recgroup.com
    Flags=$0041
    Manufacturer=REC
    Model=REC 330NP
    DataSource=Manufacturer 2018
    YearBeg=2018
    Width=0.997
    Height=1.675
    Depth=0.030
    Weight=18.000
    NPieces=100
    PriceDate=21/12/18 02:38
    Remarks, Count=5
      Str_1=Frame: black / anodized aluminium
      Str_2=Structure: Glass-EVA-PYE
      Str_3=Connections: Cable MC4
      Str_4=Mono N-Type cells
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=60
  NCelP=2
  NDiode=3
  SubModuleLayout=slTwinHalfCells
  FrontSurface=fsARCoating
  GRef=1000
  TRef=25.0
  PNom=330.0
  PNomTolLow=0.00
  PNomTolUp=1.60
  Isc=10.250
  Voc=41.30
  Imp=9.550
  Vmp=34.60
  muISC=4.10
  muVocSpec=-140.0
  muPmpReq=-0.350
  RShunt=350
  Rp_0=750
  Rp_Exp=2.00
  RSerie=0.218
  Gamma=1.061
  muGamma=-0.0004
  VMaxIEC=1000
  VMaxUL=1000
  Absorb=0.90
  ARev=3.200
  BRev=11.800
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=122.1
  SandiaAMCorr=50.000
End of PVObject pvModule
