PVObject_=pvModule
  Version=6.78
  Flags=$0043

  PVObject_Commercial=pvCommercial
    Comment=http://www.renesola.com  (P. R. China)
    Flags=$0041
    Manufacturer=Renesola
    Model=JC310M-24/Abh-b
    DataSource=Manufacturer 2014
    YearBeg=2013
    Width=0.992
    Height=1.956
    Depth=0.050
    Weight=29.000
    NPieces=100
    PriceDate=23/12/18 07:17
    Remarks, Count=5
      Str_1=Frame: Anodized Aluminum Alloy
      Str_2=Structure: Glass, Backsheet
      Str_3=Connections: JBox + Cables
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiPoly
  NCelS=72
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=310.0
  PNomTolLow=0.00
  PNomTolUp=2.00
  Isc=8.800
  Voc=45.00
  Imp=8.380
  Vmp=37.00
  muISC=3.52
  muVocSpec=-135.0
  muPmpReq=-0.400
  RShunt=2500
  Rp_0=5000
  Rp_Exp=5.50
  RSerie=0.305
  Gamma=0.957
  muGamma=-0.0002
  VMaxIEC=1000
  VMaxUL=1000
  Absorb=0.90
  ARev=3.200
  BRev=10.560
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=243.4
  SandiaAMCorr=50.000
End of PVObject pvModule
