PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.risenenergy.com (China, Germany)
    Flags=$0041
    Manufacturer=Risen Energy Co., Ltd
    Model=SYP310S
    DataSource=Manufacturer 2014
    YearBeg=2012
    Width=0.992
    Height=1.956
    Depth=0.040
    Weight=23.000
    NPieces=100
    PriceDate=23/12/18 07:18
    Remarks, Count=5
      Str_1=Frame: aluminium
      Str_2=Structure: Glass, Tedlar
      Str_3=Connections: J Box
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiPoly
  NCelS=72
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=310.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  Isc=9.050
  Voc=45.20
  Imp=8.510
  Vmp=36.40
  muISC=4.80
  muVocSpec=-144.6
  muPmpReq=-0.390
  RShunt=350
  Rp_0=1400
  Rp_Exp=5.50
  RSerie=0.372
  Gamma=1.009
  muGamma=-0.0001
  VMaxIEC=1000
  Absorb=0.90
  ARev=3.200
  BRev=10.860
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  SandiaAMCorr=50.000
End of PVObject pvModule
