PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.schueco.de (Germany)
    Flags=$0041
    Manufacturer=Schueco
    Model=MPE 240 PS 15
    DataSource=Manufacturer 2012
    YearBeg=2010
    Width=0.983
    Height=1.639
    Depth=0.042
    Weight=20.000
    NPieces=100
    PriceDate=22/12/18 16:59
    Remarks, Count=5
      Str_1=Frame: Aluminium
      Str_2
      Str_3
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiPoly
  NCelS=60
  NCelP=1
  NDiode=2
  GRef=1000
  TRef=25.0
  PNom=240.0
  PNomTolLow=-5.00
  PNomTolUp=5.00
  Isc=8.540
  Voc=37.00
  Imp=7.950
  Vmp=30.20
  muISC=4.27
  muVocSpec=0.0
  muPmpReq=-0.450
  RShunt=250
  Rp_0=1000
  Rp_Exp=5.50
  RSerie=0.325
  Gamma=0.949
  muGamma=-0.0005
  VMaxIEC=1000
  Absorb=0.90
  ARev=3.200
  BRev=10.248
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=243.4
  SandiaAMCorr=50.000
End of PVObject pvModule
