PVObject_=pvModule
  Version=6.78
  Flags=$0043

  PVObject_Commercial=pvCommercial
    Flags=$0041
    Manufacturer=Silfab
    Model=SLG 325M
    DataSource=PV Evolution Labs 2014
    YearBeg=2014
    Width=0.990
    Height=1.970
    Depth=0.038
    Weight=23.000
    NPieces=100
    PriceDate=21/12/18 03:07
    Remarks, Count=5
      Str_1
      Str_2
      Str_3
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=72
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=325.0
  PNomTolLow=0.00
  PNomTolUp=1.50
  Isc=9.254
  Voc=45.80
  Imp=8.667
  Vmp=37.50
  muISC=2.78
  muVocSpec=0.0
  muPmpReq=-0.380
  RShunt=492
  Rp_0=5152
  Rp_Exp=10.00
  RSerie=0.390
  Gamma=0.922
  muGamma=0.0000
  VMaxIEC=1000
  VMaxUL=600
  Absorb=0.90
  ARev=3.200
  BRev=11.105
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=237.4
  SandiaAMCorr=50.000
End of PVObject pvModule
