PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.siliken.com (Spain)
    Flags=$0041
    Manufacturer=Siliken
    Model=SLK72P6L 300
    DataSource=Manufacturer 2011
    YearBeg=2011
    Width=0.990
    Height=1.960
    Depth=0.040
    Weight=19.000
    NPieces=100
    PriceDate=23/12/18 05:30
    Remarks, Count=5
      Str_1=Frame: Aluminium
      Str_2
      Str_3
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiPoly
  NCelS=72
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=300.0
  PNomTolLow=-3.00
  PNomTolUp=3.00
  Isc=8.910
  Voc=44.40
  Imp=8.380
  Vmp=35.79
  muISC=5.52
  muVocSpec=0.0
  muPmpReq=-0.430
  RShunt=350
  Rp_0=1400
  Rp_Exp=5.50
  RSerie=0.369
  Gamma=0.987
  muGamma=-0.0004
  VMaxIEC=1000
  Absorb=0.90
  ARev=3.200
  BRev=10.692
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=243.4
  SandiaAMCorr=50.000
End of PVObject pvModule
