PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.sonnenstromfabrik.com (Germany)
    Flags=$0041
    Manufacturer=Sonnenstromfabrik - CS Wismar
    Model=Professional 280M60 LC
    DataSource=Manufacturer 2018
    YearBeg=2017
    Width=1.000
    Height=1.680
    Depth=0.040
    Weight=19.500
    NPieces=100
    PriceDate=23/12/18 00:38
    Remarks, Count=6
      Str_1=Frame: Aluminum
      Str_2=Structure: 3.2 mm tempered glass with AR coating, structured
      Str_3=Connections: white PET-Foil + GZX Jbox+ cable+ MC4-
      Str_4=connector
      Str_5
      Str_6
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=60
  NCelP=1
  NDiode=3
  FrontSurface=fsARCoating
  GRef=1000
  TRef=25.0
  PNom=280.0
  PNomTolLow=-3.00
  PNomTolUp=3.00
  Isc=9.460
  Voc=39.16
  Imp=8.850
  Vmp=31.64
  muISC=4.26
  muVocSpec=-121.4
  muPmpReq=-0.410
  RShunt=250
  Rp_0=1000
  Rp_Exp=5.50
  RSerie=0.317
  Gamma=1.035
  muGamma=-0.0005
  VMaxIEC=1000
  VMaxUL=600
  Absorb=0.90
  ARev=3.200
  BRev=11.352
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  SandiaAMCorr=50.000
End of PVObject pvModule
