PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.sunearthpower.com  (China)
    Flags=$0041
    Manufacturer=Sun Earth Solar Power Co Ltd
    Model=TDB156X156-48-P 175W
    DataSource=Manufacturer 2011
    YearBeg=2011
    Width=0.992
    Height=1.325
    Depth=0.046
    Weight=15.000
    NPieces=100
    PriceDate=22/12/18 11:19
    Remarks, Count=5
      Str_1=Frame: Aluminium
      Str_2=Structure: Glass-TPT
      Str_3=Connections: J. Box
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=48
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=175.0
  PNomTolLow=-3.00
  PNomTolUp=3.00
  Isc=8.010
  Voc=29.50
  Imp=7.360
  Vmp=23.80
  muISC=4.33
  muVocSpec=-102.1
  muPmpReq=-0.480
  RShunt=180
  Rp_0=700
  Rp_Exp=5.50
  RSerie=0.316
  Gamma=1.007
  muGamma=-0.0007
  VMaxIEC=1000
  Absorb=0.90
  ARev=3.200
  BRev=9.612
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=238.9
  SandiaAMCorr=50.000
End of PVObject pvModule
