PVObject_=pvModule
  Version=6.78
  Flags=$0043

  PVObject_Commercial=pvCommercial
    Comment=http://www.suniva.com/multicrystalline-modules.php
    Flags=$0041
    Manufacturer=Suniva
    Model=MVX300-72-7-701
    DataSource=Manufacturer 2013
    YearBeg=2012
    Width=0.992
    Height=1.956
    Depth=0.050
    Weight=29.000
    NPieces=100
    PriceDate=23/12/18 05:31
    Remarks, Count=5
      Str_1=Frame: Silver annodized aluminum alloy
      Str_2=Structure: Low-iron tempered glass, anti-reflective coating
      Str_3=Connections: MC4-compatible connectors
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiPoly
  NCelS=72
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=300.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  Isc=8.690
  Voc=44.80
  Imp=8.200
  Vmp=36.60
  muISC=3.91
  muVocSpec=-152.3
  muPmpReq=-0.450
  RShunt=1000
  Rp_0=4000
  Rp_Exp=5.50
  RSerie=0.325
  Gamma=1.015
  muGamma=-0.0006
  VMaxIEC=1000
  VMaxUL=1000
  Absorb=0.90
  ARev=3.200
  BRev=10.010
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=243.4
  SandiaAMCorr=50.000
End of PVObject pvModule
