PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.sunriseenergy.cn  (China)
    Flags=$0041
    Manufacturer=Sunrise
    Model=SR-M672350
    DataSource=Manufacturer 2018
    YearBeg=2014
    Width=0.992
    Height=1.956
    Depth=0.040
    Weight=22.400
    NPieces=100
    PriceDate=21/12/18 01:03
    Remarks, Count=5
      Str_1
      Str_2
      Str_3
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=72
  NCelP=1
  NDiode=3
  FrontSurface=fsNormalGlass
  GRef=1000
  TRef=25.0
  PNom=350.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  Isc=9.730
  Voc=47.07
  Imp=9.280
  Vmp=37.75
  muISC=4.87
  muVocSpec=0.0
  muPmpReq=-0.450
  RShunt=400
  Rp_0=1600
  Rp_Exp=5.50
  RSerie=0.334
  Gamma=1.021
  muGamma=-0.0010
  VMaxIEC=1000
  VMaxUL=600
  Absorb=0.90
  ARev=3.200
  BRev=11.676
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=237.4
  SandiaAMCorr=50.000
End of PVObject pvModule
