PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.swow-energy.com (China)
    Flags=$0041
    Manufacturer=Swow Energy Co. Ltd
    Model=SWE-P672-300
    DataSource=Manufacturer 2015
    YearBeg=2013
    Width=0.992
    Height=1.956
    Depth=0.040
    Weight=21.800
    NPieces=100
    PriceDate=23/12/18 05:32
    Remarks, Count=5
      Str_1=Frame: Alu or Laminate
      Str_2=Structure: Tempered glass - PA12
      Str_3=Connections: JBox+ cable + MC4 compatible
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiPoly
  NCelS=72
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=300.0
  PNomTolLow=0.00
  PNomTolUp=2.00
  Isc=8.880
  Voc=44.82
  Imp=8.260
  Vmp=36.30
  muISC=4.44
  muVocSpec=-134.5
  muPmpReq=-0.420
  RShunt=300
  Rp_0=1200
  Rp_Exp=5.50
  RSerie=0.393
  Gamma=0.997
  muGamma=-0.0003
  VMaxIEC=1000
  VMaxUL=600
  Absorb=0.90
  ARev=3.200
  BRev=10.656
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=243.4
  SandiaAMCorr=50.000
End of PVObject pvModule
