PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.talesun.com (China)
    Flags=$0041
    Manufacturer=Talesun Solar (Zhongli)
    Model=TP672P-335
    DataSource=Manufacturer 2018
    YearBeg=2016
    Width=0.992
    Height=1.968
    Depth=0.006
    Weight=22.500
    NPieces=100
    PriceDate=21/12/18 01:55
    Remarks, Count=5
      Str_1=Frame: Anodized Aluminium Alloy
      Str_2=Structure: Tempered glass
      Str_3=Connections: JBox+ cable
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiPoly
  NCelS=72
  NCelP=1
  NDiode=3
  FrontSurface=fsNormalGlass
  GRef=1000
  TRef=25.0
  PNom=335.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  Isc=9.340
  Voc=46.20
  Imp=8.820
  Vmp=38.00
  muISC=5.60
  muVocSpec=-143.2
  muPmpReq=-0.400
  RShunt=350
  Rp_0=1400
  Rp_Exp=5.50
  RSerie=0.323
  Gamma=0.930
  muGamma=-0.0005
  VMaxIEC=1000
  VMaxUL=600
  Absorb=0.90
  ARev=3.200
  BRev=10.990
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=245.6
  SandiaAMCorr=50.000
End of PVObject pvModule
