PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.talesun.com (China)
    Flags=$0041
    Manufacturer=Talesun Solar (Zhongli)
    Model=TP648M-200
    DataSource=Manufacturer 2015
    YearBeg=2011
    Width=0.990
    Height=1.324
    Depth=0.040
    Weight=15.000
    NPieces=100
    PriceDate=22/12/18 13:12
    Remarks, Count=5
      Str_1=Frame: Anodized Aluminium Alloy
      Str_2=Structure: Tempered glass
      Str_3=Connections: JBox+ cable
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=48
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=200.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  Isc=8.680
  Voc=30.10
  Imp=8.170
  Vmp=24.50
  muISC=4.34
  muVocSpec=-105.3
  muPmpReq=-0.450
  RShunt=240
  Rp_0=1000
  Rp_Exp=5.50
  RSerie=0.243
  Gamma=0.964
  muGamma=-0.0007
  VMaxIEC=1000
  VMaxUL=600
  Absorb=0.90
  ARev=3.200
  BRev=10.416
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=242.2
  SandiaAMCorr=50.000
End of PVObject pvModule
