PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.talesun.com (China)
    Flags=$0041
    Manufacturer=Talesun Solar (Zhongli)
    Model=TP660M-280
    DataSource=Manufacturer 2018
    YearBeg=2016
    Width=0.992
    Height=1.650
    Depth=0.035
    Weight=18.500
    NPieces=100
    PriceDate=23/12/18 00:46
    Remarks, Count=5
      Str_1=Frame: Anodized Aluminium Alloy
      Str_2=Structure: Tempered glass
      Str_3=Connections: JBox+ cable
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=60
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=280.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  Isc=9.350
  Voc=38.90
  Imp=8.810
  Vmp=31.80
  muISC=4.67
  muVocSpec=-116.7
  muPmpReq=-0.390
  RShunt=300
  Rp_0=1200
  Rp_Exp=5.50
  RSerie=0.284
  Gamma=0.976
  muGamma=-0.0004
  VMaxIEC=1000
  VMaxUL=600
  Absorb=0.90
  ARev=3.200
  BRev=10.540
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=244.3
  SandiaAMCorr=50.000
End of PVObject pvModule
