PVObject_=pvModule
  Version=6.78
  Flags=$0043

  PVObject_Commercial=pvCommercial
    Comment=www.trinasolar.com (China)
    Flags=$0041
    Manufacturer=Trina Solar
    Model=TSM-345DD14A(II)
    DataSource=Manufacturer 2016
    YearBeg=2015
    Width=0.992
    Height=1.956
    Depth=0.040
    Weight=27.600
    NPieces=100
    PriceDate=21/12/18 01:20
    Remarks, Count=5
      Str_1=Frame: Aluminum
      Str_2=Structure: Glass-Backsheet
      Str_3=Connections: MC4 Compatible
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=72
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=345.0
  PNomTolLow=0.00
  PNomTolUp=1.40
  Isc=9.500
  Voc=46.70
  Imp=9.000
  Vmp=38.35
  muISC=4.84
  muVocSpec=-115.8
  muPmpReq=-0.390
  RShunt=750
  Rp_0=2000
  Rp_Exp=20.00
  RSerie=0.339
  Gamma=0.941
  muGamma=-0.0004
  VMaxIEC=1500
  VMaxUL=1000
  Absorb=0.90
  ARev=3.200
  BRev=11.040
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=242.2
  SandiaAMCorr=50.000
End of PVObject pvModule
