PVObject_=pvModule
  Version=6.78
  Flags=$0043

  PVObject_Commercial=pvCommercial
    Comment=www.trinasolar.com (China)
    Flags=$0041
    Manufacturer=Trina Solar
    Model=TSM-255PD05
    DataSource=Manufacturer 2016
    YearBeg=2015
    Width=0.992
    Height=1.650
    Depth=0.035
    Weight=18.600
    NPieces=100
    PriceDate=22/12/18 19:55
    Remarks, Count=5
      Str_1=Frame: Aluminum
      Str_2=Structure: Glass-Backsheet
      Str_3=Connections: MC4 Compatiable
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiPoly
  NCelS=60
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=255.0
  PNomTolLow=0.00
  PNomTolUp=1.90
  Isc=8.880
  Voc=38.10
  Imp=8.370
  Vmp=30.50
  muISC=4.44
  muVocSpec=-118.1
  muPmpReq=-0.410
  RShunt=500
  Rp_0=1600
  Rp_Exp=16.00
  RSerie=0.353
  Gamma=1.013
  muGamma=-0.0003
  VMaxIEC=1000
  VMaxUL=1000
  Absorb=0.90
  ARev=3.200
  BRev=10.740
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=243.4
  SandiaAMCorr=50.000
End of PVObject pvModule
