PVObject_=pvModule
  Version=6.78
  Flags=$0043

  PVObject_Commercial=pvCommercial
    Comment=www.upsolar.com
    Flags=$0041
    Manufacturer=Upsolar
    Model=UP-M335P
    DataSource=Manufacturer 2016
    YearBeg=2016
    Width=0.992
    Height=1.956
    Depth=0.040
    Weight=26.500
    NPieces=100
    PriceDate=21/12/18 01:54
    Remarks, Count=5
      Str_1=Frame: Aluminium 6063-T5
      Str_2=Structure: 4.0mm tempered glass
      Str_3=Connections: EVA, backsheet
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiPoly
  NCelS=72
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=335.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  Isc=9.220
  Voc=47.00
  Imp=8.980
  Vmp=37.30
  muISC=4.61
  muVocSpec=-138.2
  muPmpReq=-0.400
  RShunt=1400
  Rp_0=5600
  Rp_Exp=5.50
  RSerie=0.320
  Gamma=0.981
  muGamma=-0.0005
  VMaxIEC=1000
  VMaxUL=1000
  Absorb=0.90
  ARev=3.200
  BRev=10.200
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=243.4
  LIDLoss=1.50
  SandiaAMCorr=50.000
End of PVObject pvModule
