PVObject_=pvModule
  Version=6.78
  Flags=$0743

  PVObject_Commercial=pvCommercial
    Comment=www.vikramsolar.com   ( India)
    Flags=$0041
    Manufacturer=Vikram Solar
    Model=Somera VSM.72.350.03.04_U
    DataSource=Manufacturer 2018
    YearBeg=2015
    Width=0.991
    Height=1.955
    Depth=0.040
    Weight=24.800
    NPieces=100
    PriceDate=23/12/18 08:35
    Remarks, Count=5
      Str_1=Frame: Anodized aluminium with twin wall profile
      Str_2=Structure: 4 mm tempered
      Str_3=Connections: EVA + White backsheet
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=72
  NCelP=1
  NDiode=3
  SubModuleLayout=slInLength
  FrontSurface=fsNormalGlass
  GRef=1000
  TRef=25.0
  PNom=350.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  Isc=9.560
  Voc=47.40
  Imp=9.180
  Vmp=38.10
  muISC=5.45
  muVocSpec=-132.7
  muPmpReq=-0.390
  RShunt=500
  Rp_0=2000
  Rp_Exp=5.50
  RSerie=0.317
  Gamma=1.005
  muGamma=-0.0006
  VMaxIEC=1000
  VMaxUL=1000
  Absorb=0.90
  ARev=3.200
  BRev=11.472
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  SandiaAMCorr=50.000
End of PVObject pvModule
