PVObject_=pvModule
  Version=6.78
  Flags=$0543

  PVObject_Commercial=pvCommercial
    Comment=www.znshine-solar.com (China)
    Flags=$0041
    Manufacturer=ZNshine Solar
    Model=ZXP6-60-230/P
    DataSource=Manufacturer 2014
    YearBeg=2014
    Width=0.992
    Height=1.640
    Depth=0.040
    Weight=19.500
    NPieces=100
    PriceDate=22/12/18 15:54
    Remarks, Count=5
      Str_1=Frame: Aluminium
      Str_2=Structure: 3.2 mm tempered
      Str_3=Connections: MC-4
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiPoly
  NCelS=60
  NCelP=1
  NDiode=3
  GRef=1000
  TRef=25.0
  PNom=230.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  Isc=8.310
  Voc=37.21
  Imp=7.840
  Vmp=29.35
  muISC=4.99
  muVocSpec=-122.8
  muPmpReq=-0.420
  RShunt=300
  Rp_0=1200
  Rp_Exp=5.50
  RSerie=0.355
  Gamma=1.066
  muGamma=-0.0003
  VMaxIEC=1000
  VMaxUL=600
  Absorb=0.90
  ARev=3.200
  BRev=9.972
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  CellArea=243.4
  SandiaAMCorr=50.000
End of PVObject pvModule
